import os, time
from sys import stdout

def red():
    RED = "\033[1;31m"
    stdout.write(RED)

def green():
    GREEN = "\033[0;32m"
    stdout.write(GREEN)

def blue():
    BLUE = "\033[1;34m"
    stdout.write(BLUE)

def yellow():
    YELLOW = "\033[1;33m"
    stdout.write(YELLOW)

def purple():
    PURPLE = "\033[1;35m"
    stdout.write(PURPLE)

def white():
    WHITE = "\033[1;37m"
    stdout.write(WHITE)

Tool = """
  ::::::::  :::    ::: 
:+:    :+: :+:    :+: 
+:+        +:+    +:+ 
+#++:++#++ +#+    +:+ 
       +#+ +#+    +#+ 
#+#    #+# #+#    #+# 
 ########   ########  
"""
Dev = "Creator: " + "Greaser"
Credits = "Credits: MannyM, OsirisL"

def menu():
    red()
    print(Tool)
    blue()
    time.sleep(1)
    print(Dev)
    green()
    print(Credits)

    yellow()
    time.sleep(1)
    print("\nPlease Choose Your SU Program!")
    time.sleep(1)
    print("\n1 --> Install CIS Course Folders")
    #time.sleep(1)
    print("\n2 --> Install Web-Dev Course Folders")
    #time.sleep(1)
    print("\n3 --> Exit")
    #time.sleep(1)
    
    option = input("\n-->> ")

    if option == "1":
        CIS()  
    if option == "2":
        Web()
    if option == "3":
        exit()
    if option == "0":
        print("Thats Not An Option!")  
        menu()
    if option >= "3":
        print("Thats Not An Option!")  
        menu() 

def CIS():
    green()
    print("[+] Creating CIS Folders...\n")

    # Creating Folders For CIS
    os.system("mkdir ~/Documents/SU_Learning/")
    os.system("mkdir ~/Documents/SU_Learning/110_BUSINESS_COMMUNICATION/")
    os.system("mkdir ~/Documents/SU_Learning/110_BUSINESS_COMMUNICATION/Week-1")
    os.system("mkdir ~/Documents/SU_Learning/110_BUSINESS_COMMUNICATION/Week-2")
    os.system("mkdir ~/Documents/SU_Learning/110_BUSINESS_COMMUNICATION/Week-3")
    os.system("mkdir ~/Documents/SU_Learning/110_BUSINESS_COMMUNICATION/Week-4")
    os.system("mkdir ~/Documents/SU_Learning/110_BUSINESS_COMMUNICATION/Week-5")
    os.system("mkdir ~/Documents/SU_Learning/110_BUSINESS_COMMUNICATION/Week-6")
    os.system("mkdir ~/Documents/SU_Learning/101_BUSINESS_MATH_FOR_SOCIAL_SCIENCES/ ")
    os.system("mkdir ~/Documents/SU_Learning/101_BUSINESS_MATH_FOR_SOCIAL_SCIENCES/Week-1 ")
    os.system("mkdir ~/Documents/SU_Learning/101_BUSINESS_MATH_FOR_SOCIAL_SCIENCES/Week-2 ")
    os.system("mkdir ~/Documents/SU_Learning/101_BUSINESS_MATH_FOR_SOCIAL_SCIENCES/Week-3 ")
    os.system("mkdir ~/Documents/SU_Learning/101_BUSINESS_MATH_FOR_SOCIAL_SCIENCES/Week-4 ")
    os.system("mkdir ~/Documents/SU_Learning/101_BUSINESS_MATH_FOR_SOCIAL_SCIENCES/Week-5 ")
    os.system("mkdir ~/Documents/SU_Learning/101_BUSINESS_MATH_FOR_SOCIAL_SCIENCES/Week-6 ")
    os.system("mkdir ~/Documents/SU_Learning/110_ALGEBRA_1/")
    os.system("mkdir ~/Documents/SU_Learning/110_ALGEBRA_1/Week-1")
    os.system("mkdir ~/Documents/SU_Learning/110_ALGEBRA_1/Week-2")
    os.system("mkdir ~/Documents/SU_Learning/110_ALGEBRA_1/Week-3")
    os.system("mkdir ~/Documents/SU_Learning/110_ALGEBRA_1/Week-4")
    os.system("mkdir ~/Documents/SU_Learning/110_ALGEBRA_1/Week-5")
    os.system("mkdir ~/Documents/SU_Learning/110_ALGEBRA_1/Week-6")
    os.system("mkdir ~/Documents/SU_Learning/110_SPREADSHEETS_1/")
    os.system("mkdir ~/Documents/SU_Learning/110_SPREADSHEETS_1/Week-1")
    os.system("mkdir ~/Documents/SU_Learning/110_SPREADSHEETS_1/Week-2")
    os.system("mkdir ~/Documents/SU_Learning/110_SPREADSHEETS_1/Week-3")
    os.system("mkdir ~/Documents/SU_Learning/110_SPREADSHEETS_1/Week-4")
    os.system("mkdir ~/Documents/SU_Learning/110_SPREADSHEETS_1/Week-5")
    os.system("mkdir ~/Documents/SU_Learning/110_SPREADSHEETS_1/Week-6")
    os.system("mkdir ~/Documents/SU_Learning/114_INTRODCUTION_TO_HTML_AND_CSS/")
    os.system("mkdir ~/Documents/SU_Learning/114_INTRODCUTION_TO_HTML_AND_CSS/Week-1")
    os.system("mkdir ~/Documents/SU_Learning/114_INTRODCUTION_TO_HTML_AND_CSS/Week-2")
    os.system("mkdir ~/Documents/SU_Learning/114_INTRODCUTION_TO_HTML_AND_CSS/Week-3")
    os.system("mkdir ~/Documents/SU_Learning/114_INTRODCUTION_TO_HTML_AND_CSS/Week-4") 
    os.system("mkdir ~/Documents/SU_Learning/114_INTRODCUTION_TO_HTML_AND_CSS/Week-5") 
    os.system("mkdir ~/Documents/SU_Learning/114_INTRODCUTION_TO_HTML_AND_CSS/Week-6") 
    os.system("mkdir ~/Documents/SU_Learning/115_HTML_AND_CSS_PROGRAMMING/")
    os.system("mkdir ~/Documents/SU_Learning/115_HTML_AND_CSS_PROGRAMMING/Week-1")
    os.system("mkdir ~/Documents/SU_Learning/115_HTML_AND_CSS_PROGRAMMING/Week-2")
    os.system("mkdir ~/Documents/SU_Learning/115_HTML_AND_CSS_PROGRAMMING/Week-3")
    os.system("mkdir ~/Documents/SU_Learning/115_HTML_AND_CSS_PROGRAMMING/Week-4")
    os.system("mkdir ~/Documents/SU_Learning/115_HTML_AND_CSS_PROGRAMMING/Week-5")
    os.system("mkdir ~/Documents/SU_Learning/115_HTML_AND_CSS_PROGRAMMING/Week-6")
    os.system("mkdir ~/Documents/SU_Learning/121_SPREADSHEETS_2/")
    os.system("mkdir ~/Documents/SU_Learning/121_SPREADSHEETS_2/Week-1")
    os.system("mkdir ~/Documents/SU_Learning/121_SPREADSHEETS_2/Week-2")
    os.system("mkdir ~/Documents/SU_Learning/121_SPREADSHEETS_2/Week-3")
    os.system("mkdir ~/Documents/SU_Learning/121_SPREADSHEETS_2/Week-4")
    os.system("mkdir ~/Documents/SU_Learning/121_SPREADSHEETS_2/Week-5")
    os.system("mkdir ~/Documents/SU_Learning/121_SPREADSHEETS_2/Week-6")
    os.system("mkdir ~/Documents/SU_Learning/133_GRAPHIC_DESIGN_1/")
    os.system("mkdir ~/Documents/SU_Learning/133_GRAPHIC_DESIGN_1/Week-1")
    os.system("mkdir ~/Documents/SU_Learning/133_GRAPHIC_DESIGN_1/Week-2")
    os.system("mkdir ~/Documents/SU_Learning/133_GRAPHIC_DESIGN_1/Week-3")
    os.system("mkdir ~/Documents/SU_Learning/133_GRAPHIC_DESIGN_1/Week-4")
    os.system("mkdir ~/Documents/SU_Learning/133_GRAPHIC_DESIGN_1/Week-5")
    os.system("mkdir ~/Documents/SU_Learning/133_GRAPHIC_DESIGN_1/Week-6")
    os.system("mkdir ~/Documents/SU_Learning/145_GRAPHIC_DESIGN_2/")
    os.system("mkdir ~/Documents/SU_Learning/145_GRAPHIC_DESIGN_2/Week-1")
    os.system("mkdir ~/Documents/SU_Learning/145_GRAPHIC_DESIGN_2/Week-2")
    os.system("mkdir ~/Documents/SU_Learning/145_GRAPHIC_DESIGN_2/Week-3")
    os.system("mkdir ~/Documents/SU_Learning/145_GRAPHIC_DESIGN_2/Week-4")
    os.system("mkdir ~/Documents/SU_Learning/145_GRAPHIC_DESIGN_2/Week-5")
    os.system("mkdir ~/Documents/SU_Learning/145_GRAPHIC_DESIGN_2/Week-6")
    os.system("mkdir ~/Documents/SU_Learning/131_INTRODUCTION_TO_COMPUTER_PROGRAMMING/")
    os.system("mkdir ~/Documents/SU_Learning/131_INTRODUCTION_TO_COMPUTER_PROGRAMMING/Week-1")
    os.system("mkdir ~/Documents/SU_Learning/131_INTRODUCTION_TO_COMPUTER_PROGRAMMING/Week-2")
    os.system("mkdir ~/Documents/SU_Learning/131_INTRODUCTION_TO_COMPUTER_PROGRAMMING/Week-3")
    os.system("mkdir ~/Documents/SU_Learning/131_INTRODUCTION_TO_COMPUTER_PROGRAMMING/Week-4")
    os.system("mkdir ~/Documents/SU_Learning/131_INTRODUCTION_TO_COMPUTER_PROGRAMMING/Week-5")
    os.system("mkdir ~/Documents/SU_Learning/131_INTRODUCTION_TO_COMPUTER_PROGRAMMING/Week-6")
    os.system("mkdir ~/Documents/SU_Learning/132_OBJECT_ORIENTED_PROGRAMMING/")
    os.system("mkdir ~/Documents/SU_Learning/132_OBJECT_ORIENTED_PROGRAMMING/Week-1")
    os.system("mkdir ~/Documents/SU_Learning/132_OBJECT_ORIENTED_PROGRAMMING/Week-2")
    os.system("mkdir ~/Documents/SU_Learning/132_OBJECT_ORIENTED_PROGRAMMING/Week-3")
    os.system("mkdir ~/Documents/SU_Learning/132_OBJECT_ORIENTED_PROGRAMMING/Week-4")
    os.system("mkdir ~/Documents/SU_Learning/132_OBJECT_ORIENTED_PROGRAMMING/Week-5")
    os.system("mkdir ~/Documents/SU_Learning/132_OBJECT_ORIENTED_PROGRAMMING/Week-6")
    os.system("mkdir ~/Documents/SU_Learning/133_ALGORITHMS_AND_DATA_STRUCTURES/")
    os.system("mkdir ~/Documents/SU_Learning/133_ALGORITHMS_AND_DATA_STRUCTURES/Week-1")
    os.system("mkdir ~/Documents/SU_Learning/133_ALGORITHMS_AND_DATA_STRUCTURES/Week-2")
    os.system("mkdir ~/Documents/SU_Learning/133_ALGORITHMS_AND_DATA_STRUCTURES/Week-3")
    os.system("mkdir ~/Documents/SU_Learning/133_ALGORITHMS_AND_DATA_STRUCTURES/Week-4")
    os.system("mkdir ~/Documents/SU_Learning/133_ALGORITHMS_AND_DATA_STRUCTURES/Week-5")
    os.system("mkdir ~/Documents/SU_Learning/133_ALGORITHMS_AND_DATA_STRUCTURES/Week-6")
    os.system("mkdir ~/Documents/SU_Learning/121_COLLEGE_STUDIES/")
    os.system("mkdir ~/Documents/SU_Learning/121_COLLEGE_STUDIES/Week-1")
    os.system("mkdir ~/Documents/SU_Learning/121_COLLEGE_STUDIES/Week-2")
    os.system("mkdir ~/Documents/SU_Learning/121_COLLEGE_STUDIES/Week-3")
    os.system("mkdir ~/Documents/SU_Learning/121_COLLEGE_STUDIES/Week-4")
    os.system("mkdir ~/Documents/SU_Learning/121_COLLEGE_STUDIES/Week-5")
    os.system("mkdir ~/Documents/SU_Learning/121_COLLEGE_STUDIES/Week-6")
    os.system("mkdir ~/Documents/SU_Learning/133_READING_COMPREHENSION/")
    os.system("mkdir ~/Documents/SU_Learning/133_READING_COMPREHENSION/Week-1")
    os.system("mkdir ~/Documents/SU_Learning/133_READING_COMPREHENSION/Week-2")
    os.system("mkdir ~/Documents/SU_Learning/133_READING_COMPREHENSION/Week-3")
    os.system("mkdir ~/Documents/SU_Learning/133_READING_COMPREHENSION/Week-4")
    os.system("mkdir ~/Documents/SU_Learning/133_READING_COMPREHENSION/Week-5")
    os.system("mkdir ~/Documents/SU_Learning/133_READING_COMPREHENSION/Week-6")
    os.system("mkdir ~/Documents/SU_Learning/145_TECHNICAL_WRITING/")
    os.system("mkdir ~/Documents/SU_Learning/145_TECHNICAL_WRITING/Week-1")
    os.system("mkdir ~/Documents/SU_Learning/145_TECHNICAL_WRITING/Week-2")
    os.system("mkdir ~/Documents/SU_Learning/145_TECHNICAL_WRITING/Week-3")
    os.system("mkdir ~/Documents/SU_Learning/145_TECHNICAL_WRITING/Week-4")
    os.system("mkdir ~/Documents/SU_Learning/145_TECHNICAL_WRITING/Week-5")
    os.system("mkdir ~/Documents/SU_Learning/145_TECHNICAL_WRITING/Week-6")
    os.system("mkdir ~/Documents/SU_Learning/122_HARDWARE_AND_NETWORK_TROUBLESHOOTING_AND_CLOUD_COMPUTING/")
    os.system("mkdir ~/Documents/SU_Learning/122_HARDWARE_AND_NETWORK_TROUBLESHOOTING_AND_CLOUD_COMPUTING/Week-1")
    os.system("mkdir ~/Documents/SU_Learning/122_HARDWARE_AND_NETWORK_TROUBLESHOOTING_AND_CLOUD_COMPUTING/Week-2")
    os.system("mkdir ~/Documents/SU_Learning/122_HARDWARE_AND_NETWORK_TROUBLESHOOTING_AND_CLOUD_COMPUTING/Week-3")
    os.system("mkdir ~/Documents/SU_Learning/122_HARDWARE_AND_NETWORK_TROUBLESHOOTING_AND_CLOUD_COMPUTING/Week-4")
    os.system("mkdir ~/Documents/SU_Learning/122_HARDWARE_AND_NETWORK_TROUBLESHOOTING_AND_CLOUD_COMPUTING/Week-5")
    os.system("mkdir ~/Documents/SU_Learning/122_HARDWARE_AND_NETWORK_TROUBLESHOOTING_AND_CLOUD_COMPUTING/Week-6")
    os.system("mkdir ~/Documents/SU_Learning/101_GEOLOGY_1/")
    os.system("mkdir ~/Documents/SU_Learning/101_GEOLOGY_1/Week-1")
    os.system("mkdir ~/Documents/SU_Learning/101_GEOLOGY_1/Week-2")
    os.system("mkdir ~/Documents/SU_Learning/101_GEOLOGY_1/Week-3")
    os.system("mkdir ~/Documents/SU_Learning/101_GEOLOGY_1/Week-4")
    os.system("mkdir ~/Documents/SU_Learning/101_GEOLOGY_1/Week-5")
    os.system("mkdir ~/Documents/SU_Learning/101_GEOLOGY_1/Week-6")
    os.system("mkdir ~/Documents/SU_Learning/131_OPERATING_SYSTEMS_AND_SECURITY/")
    os.system("mkdir ~/Documents/SU_Learning/131_OPERATING_SYSTEMS_AND_SECURITY/Week-1")
    os.system("mkdir ~/Documents/SU_Learning/131_OPERATING_SYSTEMS_AND_SECURITY/Week-2")
    os.system("mkdir ~/Documents/SU_Learning/131_OPERATING_SYSTEMS_AND_SECURITY/Week-3")
    os.system("mkdir ~/Documents/SU_Learning/131_OPERATING_SYSTEMS_AND_SECURITY/Week-4")
    os.system("mkdir ~/Documents/SU_Learning/131_OPERATING_SYSTEMS_AND_SECURITY/Week-5")
    os.system("mkdir ~/Documents/SU_Learning/131_OPERATING_SYSTEMS_AND_SECURITY/Week-6")
    os.system("mkdir ~/Documents/SU_Learning/121_INTRODUCTION_TO_COMPUTER_HARDWARE/")
    os.system("mkdir ~/Documents/SU_Learning/121_INTRODUCTION_TO_COMPUTER_HARDWARE/Week-1")
    os.system("mkdir ~/Documents/SU_Learning/121_INTRODUCTION_TO_COMPUTER_HARDWARE/Week-2")
    os.system("mkdir ~/Documents/SU_Learning/121_INTRODUCTION_TO_COMPUTER_HARDWARE/Week-3")
    os.system("mkdir ~/Documents/SU_Learning/121_INTRODUCTION_TO_COMPUTER_HARDWARE/Week-4")
    os.system("mkdir ~/Documents/SU_Learning/121_INTRODUCTION_TO_COMPUTER_HARDWARE/Week-5")
    os.system("mkdir ~/Documents/SU_Learning/121_INTRODUCTION_TO_COMPUTER_HARDWARE/Week-6")
    os.system("mkdir ~/Documents/SU_Learning/132_SOFTWARE_TROUBLESHOOTING_AND_OPERATIONAL_PROCEDURES/")
    os.system("mkdir ~/Documents/SU_Learning/132_SOFTWARE_TROUBLESHOOTING_AND_OPERATIONAL_PROCEDURES/Week-1")
    os.system("mkdir ~/Documents/SU_Learning/132_SOFTWARE_TROUBLESHOOTING_AND_OPERATIONAL_PROCEDURES/Week-2")
    os.system("mkdir ~/Documents/SU_Learning/132_SOFTWARE_TROUBLESHOOTING_AND_OPERATIONAL_PROCEDURES/Week-3")
    os.system("mkdir ~/Documents/SU_Learning/132_SOFTWARE_TROUBLESHOOTING_AND_OPERATIONAL_PROCEDURES/Week-4")
    os.system("mkdir ~/Documents/SU_Learning/132_SOFTWARE_TROUBLESHOOTING_AND_OPERATIONAL_PROCEDURES/Week-5")
    os.system("mkdir ~/Documents/SU_Learning/132_SOFTWARE_TROUBLESHOOTING_AND_OPERATIONAL_PROCEDURES/Week-6")
    os.system("mkdir ~/Documents/SU_Learning/141_NETWORKING_CONCEPTS_AND_INFRASTRUCTURE/")
    os.system("mkdir ~/Documents/SU_Learning/141_NETWORKING_CONCEPTS_AND_INFRASTRUCTURE/Week-1")
    os.system("mkdir ~/Documents/SU_Learning/141_NETWORKING_CONCEPTS_AND_INFRASTRUCTURE/Week-2")
    os.system("mkdir ~/Documents/SU_Learning/141_NETWORKING_CONCEPTS_AND_INFRASTRUCTURE/Week-3")
    os.system("mkdir ~/Documents/SU_Learning/141_NETWORKING_CONCEPTS_AND_INFRASTRUCTURE/Week-4")
    os.system("mkdir ~/Documents/SU_Learning/141_NETWORKING_CONCEPTS_AND_INFRASTRUCTURE/Week-5")
    os.system("mkdir ~/Documents/SU_Learning/141_NETWORKING_CONCEPTS_AND_INFRASTRUCTURE/Week-6")
    os.system("mkdir ~/Documents/SU_Learning/142_NETWORKING_OPERATIONS_SECURITY_AND_TROUBLESHOOTING/")
    os.system("mkdir ~/Documents/SU_Learning/142_NETWORKING_OPERATIONS_SECURITY_AND_TROUBLESHOOTING/Week-1")
    os.system("mkdir ~/Documents/SU_Learning/142_NETWORKING_OPERATIONS_SECURITY_AND_TROUBLESHOOTING/Week-2")
    os.system("mkdir ~/Documents/SU_Learning/142_NETWORKING_OPERATIONS_SECURITY_AND_TROUBLESHOOTING/Week-3")
    os.system("mkdir ~/Documents/SU_Learning/142_NETWORKING_OPERATIONS_SECURITY_AND_TROUBLESHOOTING/Week-4")
    os.system("mkdir ~/Documents/SU_Learning/142_NETWORKING_OPERATIONS_SECURITY_AND_TROUBLESHOOTING/Week-5")
    os.system("mkdir ~/Documents/SU_Learning/142_NETWORKING_OPERATIONS_SECURITY_AND_TROUBLESHOOTING/Week-6")
    os.system("mkdir ~/Documents/SU_Learning/143_SECURITY_THREATS_TECHNOLOGIES_AND_ARCHITECTURE/")
    os.system("mkdir ~/Documents/SU_Learning/143_SECURITY_THREATS_TECHNOLOGIES_AND_ARCHITECTURE/Week-1")
    os.system("mkdir ~/Documents/SU_Learning/143_SECURITY_THREATS_TECHNOLOGIES_AND_ARCHITECTURE/Week-2")
    os.system("mkdir ~/Documents/SU_Learning/143_SECURITY_THREATS_TECHNOLOGIES_AND_ARCHITECTURE/Week-3")
    os.system("mkdir ~/Documents/SU_Learning/143_SECURITY_THREATS_TECHNOLOGIES_AND_ARCHITECTURE/Week-4")
    os.system("mkdir ~/Documents/SU_Learning/143_SECURITY_THREATS_TECHNOLOGIES_AND_ARCHITECTURE/Week-5")
    os.system("mkdir ~/Documents/SU_Learning/143_SECURITY_THREATS_TECHNOLOGIES_AND_ARCHITECTURE/Week-6")
    os.system("mkdir ~/Documents/SU_Learning/144_SECURITY_ACCESS_MANAGEMENT_AND_CRYPTOGRAPHY/")
    os.system("mkdir ~/Documents/SU_Learning/144_SECURITY_ACCESS_MANAGEMENT_AND_CRYPTOGRAPHY/Week-1")
    os.system("mkdir ~/Documents/SU_Learning/144_SECURITY_ACCESS_MANAGEMENT_AND_CRYPTOGRAPHY/Week-2")
    os.system("mkdir ~/Documents/SU_Learning/144_SECURITY_ACCESS_MANAGEMENT_AND_CRYPTOGRAPHY/Week-3")
    os.system("mkdir ~/Documents/SU_Learning/144_SECURITY_ACCESS_MANAGEMENT_AND_CRYPTOGRAPHY/Week-4")
    os.system("mkdir ~/Documents/SU_Learning/144_SECURITY_ACCESS_MANAGEMENT_AND_CRYPTOGRAPHY/Week-5")
    os.system("mkdir ~/Documents/SU_Learning/144_SECURITY_ACCESS_MANAGEMENT_AND_CRYPTOGRAPHY/Week-6")
    os.system("mkdir ~/Documents/SU_Learning/145_CYBERSECURITY_THREAT_AND_VULNERABILITY_MANAGEMENT/")
    os.system("mkdir ~/Documents/SU_Learning/145_CYBERSECURITY_THREAT_AND_VULNERABILITY_MANAGEMENT/Week-1")
    os.system("mkdir ~/Documents/SU_Learning/145_CYBERSECURITY_THREAT_AND_VULNERABILITY_MANAGEMENT/Week-2")
    os.system("mkdir ~/Documents/SU_Learning/145_CYBERSECURITY_THREAT_AND_VULNERABILITY_MANAGEMENT/Week-3")
    os.system("mkdir ~/Documents/SU_Learning/145_CYBERSECURITY_THREAT_AND_VULNERABILITY_MANAGEMENT/Week-4")
    os.system("mkdir ~/Documents/SU_Learning/145_CYBERSECURITY_THREAT_AND_VULNERABILITY_MANAGEMENT/Week-5")
    os.system("mkdir ~/Documents/SU_Learning/145_CYBERSECURITY_THREAT_AND_VULNERABILITY_MANAGEMENT/Week-6")
    os.system("mkdir ~/Documents/SU_Learning/146_CYBERSECURITY_INCIDENT_RESPONSE_AND_SECURITY_ARCHITECTURE/")
    os.system("mkdir ~/Documents/SU_Learning/146_CYBERSECURITY_INCIDENT_RESPONSE_AND_SECURITY_ARCHITECTURE/Week-1")
    os.system("mkdir ~/Documents/SU_Learning/146_CYBERSECURITY_INCIDENT_RESPONSE_AND_SECURITY_ARCHITECTURE/Week-2")
    os.system("mkdir ~/Documents/SU_Learning/146_CYBERSECURITY_INCIDENT_RESPONSE_AND_SECURITY_ARCHITECTURE/Week-3")
    os.system("mkdir ~/Documents/SU_Learning/146_CYBERSECURITY_INCIDENT_RESPONSE_AND_SECURITY_ARCHITECTURE/Week-4")
    os.system("mkdir ~/Documents/SU_Learning/146_CYBERSECURITY_INCIDENT_RESPONSE_AND_SECURITY_ARCHITECTURE/Week-5")
    os.system("mkdir ~/Documents/SU_Learning/146_CYBERSECURITY_INCIDENT_RESPONSE_AND_SECURITY_ARCHITECTURE/Week-6")
    os.system("mkdir ~/Documents/SU_Learning/110_INTRODUCTION_TO_PSYCHOLOGY/")
    os.system("mkdir ~/Documents/SU_Learning/110_INTRODUCTION_TO_PSYCHOLOGY/Week-1")
    os.system("mkdir ~/Documents/SU_Learning/110_INTRODUCTION_TO_PSYCHOLOGY/Week-2")
    os.system("mkdir ~/Documents/SU_Learning/110_INTRODUCTION_TO_PSYCHOLOGY/Week-3")
    os.system("mkdir ~/Documents/SU_Learning/110_INTRODUCTION_TO_PSYCHOLOGY/Week-4")
    os.system("mkdir ~/Documents/SU_Learning/110_INTRODUCTION_TO_PSYCHOLOGY/Week-5")
    os.system("mkdir ~/Documents/SU_Learning/110_INTRODUCTION_TO_PSYCHOLOGY/Week-6")
    os.system("mkdir ~/Documents/SU_Learning/191_INTRODUCTION_TO_JAVASCRIPT/")
    os.system("mkdir ~/Documents/SU_Learning/191_INTRODUCTION_TO_JAVASCRIPT/week-1")
    os.system("mkdir ~/Documents/SU_Learning/191_INTRODUCTION_TO_JAVASCRIPT/week-2")
    os.system("mkdir ~/Documents/SU_Learning/191_INTRODUCTION_TO_JAVASCRIPT/week-3")
    os.system("mkdir ~/Documents/SU_Learning/191_INTRODUCTION_TO_JAVASCRIPT/week-4")
    os.system("mkdir ~/Documents/SU_Learning/191_INTRODUCTION_TO_JAVASCRIPT/week-5")
    os.system("mkdir ~/Documents/SU_Learning/191_INTRODUCTION_TO_JAVASCRIPT/week-6")
    os.system("mkdir ~/Documents/SU_Learning/192_JAVASCRIPT_PROGRAMMING/")
    os.system("mkdir ~/Documents/SU_Learning/192_JAVASCRIPT_PROGRAMMING/Week-1")
    os.system("mkdir ~/Documents/SU_Learning/192_JAVASCRIPT_PROGRAMMING/Week-2")
    os.system("mkdir ~/Documents/SU_Learning/192_JAVASCRIPT_PROGRAMMING/Week-3")
    os.system("mkdir ~/Documents/SU_Learning/192_JAVASCRIPT_PROGRAMMING/Week-4")
    os.system("mkdir ~/Documents/SU_Learning/192_JAVASCRIPT_PROGRAMMING/Week-5")
    os.system("mkdir ~/Documents/SU_Learning/192_JAVASCRIPT_PROGRAMMING/Week-6")
    os.system("mkdir ~/Documents/SU_Learning/101_WORD_PROCESSING/")
    os.system("mkdir ~/Documents/SU_Learning/101_WORD_PROCESSING/Week-1")
    os.system("mkdir ~/Documents/SU_Learning/101_WORD_PROCESSING/Week-2")
    os.system("mkdir ~/Documents/SU_Learning/101_WORD_PROCESSING/Week-3")
    os.system("mkdir ~/Documents/SU_Learning/101_WORD_PROCESSING/Week-4")
    os.system("mkdir ~/Documents/SU_Learning/101_WORD_PROCESSING/Week-5")
    os.system("mkdir ~/Documents/SU_Learning/101_WORD_PROCESSING/Week-6")

    time.sleep(2)
    print("[+] Folders Created, Happy Learning! :)")

def Web():
    green()
    print("[+] Creating Web Development Folders...\n")

    # Creating Folders For Web Dev
    os.system("mkdir ~/Documents/SU_Learning/")
    os.system("mkdir ~/Documents/SU_Learning/110_ALGEBRA_1/")
    os.system("mkdir ~/Documents/SU_Learning/110_ALGEBRA_1/Week-1")
    os.system("mkdir ~/Documents/SU_Learning/110_ALGEBRA_1/Week-2")
    os.system("mkdir ~/Documents/SU_Learning/110_ALGEBRA_1/Week-3")
    os.system("mkdir ~/Documents/SU_Learning/110_ALGEBRA_1/Week-4")
    os.system("mkdir ~/Documents/SU_Learning/110_ALGEBRA_1/Week-5")
    os.system("mkdir ~/Documents/SU_Learning/110_ALGEBRA_1/Week-6")
    os.system("mkdir ~/Documents/SU_Learning/110_INTRODUCTION_TO_SWIFT/ ")
    os.system("mkdir ~/Documents/SU_Learning/110_INTRODUCTION_TO_SWIFT/Week-1 ")
    os.system("mkdir ~/Documents/SU_Learning/110_INTRODUCTION_TO_SWIFT/Week-2 ")
    os.system("mkdir ~/Documents/SU_Learning/110_INTRODUCTION_TO_SWIFT/Week-3 ")
    os.system("mkdir ~/Documents/SU_Learning/110_INTRODUCTION_TO_SWIFT/Week-4 ")
    os.system("mkdir ~/Documents/SU_Learning/110_INTRODUCTION_TO_SWIFT/Week-5 ")
    os.system("mkdir ~/Documents/SU_Learning/110_INTRODUCTION_TO_SWIFT/Week-6 ")
    os.system("mkdir ~/Documents/SU_Learning/121_DATA_TYPES_AND_CONTROL_STRUCTURES_IN_SWIFT/")
    os.system("mkdir ~/Documents/SU_Learning/121_DATA_TYPES_AND_CONTROL_STRUCTURES_IN_SWIFT/Week-1")
    os.system("mkdir ~/Documents/SU_Learning/121_DATA_TYPES_AND_CONTROL_STRUCTURES_IN_SWIFT/Week-2")
    os.system("mkdir ~/Documents/SU_Learning/121_DATA_TYPES_AND_CONTROL_STRUCTURES_IN_SWIFT/Week-3")
    os.system("mkdir ~/Documents/SU_Learning/121_DATA_TYPES_AND_CONTROL_STRUCTURES_IN_SWIFT/Week-4")
    os.system("mkdir ~/Documents/SU_Learning/121_DATA_TYPES_AND_CONTROL_STRUCTURES_IN_SWIFT/Week-5")
    os.system("mkdir ~/Documents/SU_Learning/121_DATA_TYPES_AND_CONTROL_STRUCTURES_IN_SWIFT/Week-6")
    os.system("mkdir ~/Documents/SU_Learning/133_DATA_STRUCTURES_IN_SWIFT/")
    os.system("mkdir ~/Documents/SU_Learning/133_DATA_STRUCTURES_IN_SWIFT/Week-1")
    os.system("mkdir ~/Documents/SU_Learning/133_DATA_STRUCTURES_IN_SWIFT/Week-2")
    os.system("mkdir ~/Documents/SU_Learning/133_DATA_STRUCTURES_IN_SWIFT/Week-3")
    os.system("mkdir ~/Documents/SU_Learning/133_DATA_STRUCTURES_IN_SWIFT/Week-4")
    os.system("mkdir ~/Documents/SU_Learning/133_DATA_STRUCTURES_IN_SWIFT/Week-5")
    os.system("mkdir ~/Documents/SU_Learning/133_DATA_STRUCTURES_IN_SWIFT/Week-6")
    os.system("mkdir ~/Documents/SU_Learning/210_INTRODUCTION_TO_APP_DEVELOPMENT/")
    os.system("mkdir ~/Documents/SU_Learning/210_INTRODUCTION_TO_APP_DEVELOPMENT/Week-1")
    os.system("mkdir ~/Documents/SU_Learning/210_INTRODUCTION_TO_APP_DEVELOPMENT/Week-2")
    os.system("mkdir ~/Documents/SU_Learning/210_INTRODUCTION_TO_APP_DEVELOPMENT/Week-3")
    os.system("mkdir ~/Documents/SU_Learning/210_INTRODUCTION_TO_APP_DEVELOPMENT/Week-4") 
    os.system("mkdir ~/Documents/SU_Learning/210_INTRODUCTION_TO_APP_DEVELOPMENT/Week-5") 
    os.system("mkdir ~/Documents/SU_Learning/210_INTRODUCTION_TO_APP_DEVELOPMENT/Week-6") 
    os.system("mkdir ~/Documents/SU_Learning/220_INTRODUCTION_TO_UIKIT/")
    os.system("mkdir ~/Documents/SU_Learning/220_INTRODUCTION_TO_UIKIT/Week-1")
    os.system("mkdir ~/Documents/SU_Learning/220_INTRODUCTION_TO_UIKIT/Week-2")
    os.system("mkdir ~/Documents/SU_Learning/220_INTRODUCTION_TO_UIKIT/Week-3")
    os.system("mkdir ~/Documents/SU_Learning/220_INTRODUCTION_TO_UIKIT/Week-4")
    os.system("mkdir ~/Documents/SU_Learning/220_INTRODUCTION_TO_UIKIT/Week-5")
    os.system("mkdir ~/Documents/SU_Learning/220_INTRODUCTION_TO_UIKIT/Week-6")
    os.system("mkdir ~/Documents/SU_Learning/230_TABLES_AND_PERSISTANCE/")
    os.system("mkdir ~/Documents/SU_Learning/230_TABLES_AND_PERSISTANCE/Week-1")
    os.system("mkdir ~/Documents/SU_Learning/230_TABLES_AND_PERSISTANCE/Week-2")
    os.system("mkdir ~/Documents/SU_Learning/230_TABLES_AND_PERSISTANCE/Week-3")
    os.system("mkdir ~/Documents/SU_Learning/230_TABLES_AND_PERSISTANCE/Week-4")
    os.system("mkdir ~/Documents/SU_Learning/230_TABLES_AND_PERSISTANCE/Week-5")
    os.system("mkdir ~/Documents/SU_Learning/230_TABLES_AND_PERSISTANCE/Week-6")
    os.system("mkdir ~/Documents/SU_Learning/240_NAVIGATION_AND_WORKFLOWS/")
    os.system("mkdir ~/Documents/SU_Learning/240_NAVIGATION_AND_WORKFLOWS/Week-1")
    os.system("mkdir ~/Documents/SU_Learning/240_NAVIGATION_AND_WORKFLOWS/Week-2")
    os.system("mkdir ~/Documents/SU_Learning/240_NAVIGATION_AND_WORKFLOWS/Week-3")
    os.system("mkdir ~/Documents/SU_Learning/240_NAVIGATION_AND_WORKFLOWS/Week-4")
    os.system("mkdir ~/Documents/SU_Learning/240_NAVIGATION_AND_WORKFLOWS/Week-5")
    os.system("mkdir ~/Documents/SU_Learning/240_NAVIGATION_AND_WORKFLOWS/Week-6")
    os.system("mkdir ~/Documents/SU_Learning/250_WORKING_WITH_THE_WEB/")
    os.system("mkdir ~/Documents/SU_Learning/250_WORKING_WITH_THE_WEB/Week-1")
    os.system("mkdir ~/Documents/SU_Learning/250_WORKING_WITH_THE_WEB/Week-2")
    os.system("mkdir ~/Documents/SU_Learning/250_WORKING_WITH_THE_WEB/Week-3")
    os.system("mkdir ~/Documents/SU_Learning/250_WORKING_WITH_THE_WEB/Week-4")
    os.system("mkdir ~/Documents/SU_Learning/250_WORKING_WITH_THE_WEB/Week-5")
    os.system("mkdir ~/Documents/SU_Learning/250_WORKING_WITH_THE_WEB/Week-6")
    os.system("mkdir ~/Documents/SU_Learning/260_PROTOTYPING_AND_PROJECT_PLANNING/")
    os.system("mkdir ~/Documents/SU_Learning/260_PROTOTYPING_AND_PROJECT_PLANNING/Week-1")
    os.system("mkdir ~/Documents/SU_Learning/260_PROTOTYPING_AND_PROJECT_PLANNING/Week-2")
    os.system("mkdir ~/Documents/SU_Learning/260_PROTOTYPING_AND_PROJECT_PLANNING/Week-3")
    os.system("mkdir ~/Documents/SU_Learning/260_PROTOTYPING_AND_PROJECT_PLANNING/Week-4")
    os.system("mkdir ~/Documents/SU_Learning/260_PROTOTYPING_AND_PROJECT_PLANNING/Week-5")
    os.system("mkdir ~/Documents/SU_Learning/260_PROTOTYPING_AND_PROJECT_PLANNING/Week-6")
    os.system("mkdir ~/Documents/SU_Learning/110_BUSINESS_COMMUNICATION/")
    os.system("mkdir ~/Documents/SU_Learning/110_BUSINESS_COMMUNICATION/Week-1")
    os.system("mkdir ~/Documents/SU_Learning/110_BUSINESS_COMMUNICATION/Week-2")
    os.system("mkdir ~/Documents/SU_Learning/110_BUSINESS_COMMUNICATION/Week-3")
    os.system("mkdir ~/Documents/SU_Learning/110_BUSINESS_COMMUNICATION/Week-4")
    os.system("mkdir ~/Documents/SU_Learning/110_BUSINESS_COMMUNICATION/Week-5")
    os.system("mkdir ~/Documents/SU_Learning/110_BUSINESS_COMMUNICATION/Week-6")
    os.system("mkdir ~/Documents/SU_Learning/101_BUSINESS_MATH_FOR_SOCIAL_SCIENCES/")
    os.system("mkdir ~/Documents/SU_Learning/101_BUSINESS_MATH_FOR_SOCIAL_SCIENCES/Week-1")
    os.system("mkdir ~/Documents/SU_Learning/101_BUSINESS_MATH_FOR_SOCIAL_SCIENCES/Week-2")
    os.system("mkdir ~/Documents/SU_Learning/101_BUSINESS_MATH_FOR_SOCIAL_SCIENCES/Week-3")
    os.system("mkdir ~/Documents/SU_Learning/101_BUSINESS_MATH_FOR_SOCIAL_SCIENCES/Week-4")
    os.system("mkdir ~/Documents/SU_Learning/101_BUSINESS_MATH_FOR_SOCIAL_SCIENCES/Week-5")
    os.system("mkdir ~/Documents/SU_Learning/101_BUSINESS_MATH_FOR_SOCIAL_SCIENCES/Week-6")
    os.system("mkdir ~/Documents/SU_Learning/114_INTRODUCTION_TO_HTML_AND_CSS/")
    os.system("mkdir ~/Documents/SU_Learning/114_INTRODUCTION_TO_HTML_AND_CSS/Week-1")
    os.system("mkdir ~/Documents/SU_Learning/114_INTRODUCTION_TO_HTML_AND_CSS/Week-2")
    os.system("mkdir ~/Documents/SU_Learning/114_INTRODUCTION_TO_HTML_AND_CSS/Week-3")
    os.system("mkdir ~/Documents/SU_Learning/114_INTRODUCTION_TO_HTML_AND_CSS/Week-4")
    os.system("mkdir ~/Documents/SU_Learning/114_INTRODUCTION_TO_HTML_AND_CSS/Week-5")
    os.system("mkdir ~/Documents/SU_Learning/114_INTRODUCTION_TO_HTML_AND_CSS/Week-6")
    os.system("mkdir ~/Documents/SU_Learning/115_HTML_AND_CSS_PROGRAMMING/")
    os.system("mkdir ~/Documents/SU_Learning/115_HTML_AND_CSS_PROGRAMMING/Week-1")
    os.system("mkdir ~/Documents/SU_Learning/115_HTML_AND_CSS_PROGRAMMING/Week-2")
    os.system("mkdir ~/Documents/SU_Learning/115_HTML_AND_CSS_PROGRAMMING/Week-3")
    os.system("mkdir ~/Documents/SU_Learning/115_HTML_AND_CSS_PROGRAMMING/Week-4")
    os.system("mkdir ~/Documents/SU_Learning/115_HTML_AND_CSS_PROGRAMMING/Week-5")
    os.system("mkdir ~/Documents/SU_Learning/115_HTML_AND_CSS_PROGRAMMING/Week-6")
    os.system("mkdir ~/Documents/SU_Learning/133_GRAPHIC_DESIGN_1/")
    os.system("mkdir ~/Documents/SU_Learning/133_GRAPHIC_DESIGN_1/Week-1")
    os.system("mkdir ~/Documents/SU_Learning/133_GRAPHIC_DESIGN_1/Week-2")
    os.system("mkdir ~/Documents/SU_Learning/133_GRAPHIC_DESIGN_1/Week-3")
    os.system("mkdir ~/Documents/SU_Learning/133_GRAPHIC_DESIGN_1/Week-4")
    os.system("mkdir ~/Documents/SU_Learning/133_GRAPHIC_DESIGN_1/Week-5")
    os.system("mkdir ~/Documents/SU_Learning/133_GRAPHIC_DESIGN_1/Week-6")
    os.system("mkdir ~/Documents/SU_Learning/145_GRAPHIC_DESIGN_2/")
    os.system("mkdir ~/Documents/SU_Learning/145_GRAPHIC_DESIGN_2/Week-1")
    os.system("mkdir ~/Documents/SU_Learning/145_GRAPHIC_DESIGN_2/Week-2")
    os.system("mkdir ~/Documents/SU_Learning/145_GRAPHIC_DESIGN_2/Week-3")
    os.system("mkdir ~/Documents/SU_Learning/145_GRAPHIC_DESIGN_2/Week-4")
    os.system("mkdir ~/Documents/SU_Learning/145_GRAPHIC_DESIGN_2/Week-5")
    os.system("mkdir ~/Documents/SU_Learning/145_GRAPHIC_DESIGN_2/Week-6")
    os.system("mkdir ~/Documents/SU_Learning/131_INTRODUCTION_TO_COMPUTER_PROGRAMMING/")
    os.system("mkdir ~/Documents/SU_Learning/131_INTRODUCTION_TO_COMPUTER_PROGRAMMING/Week-1")
    os.system("mkdir ~/Documents/SU_Learning/131_INTRODUCTION_TO_COMPUTER_PROGRAMMING/Week-2")
    os.system("mkdir ~/Documents/SU_Learning/131_INTRODUCTION_TO_COMPUTER_PROGRAMMING/Week-3")
    os.system("mkdir ~/Documents/SU_Learning/131_INTRODUCTION_TO_COMPUTER_PROGRAMMING/Week-4")
    os.system("mkdir ~/Documents/SU_Learning/131_INTRODUCTION_TO_COMPUTER_PROGRAMMING/Week-5")
    os.system("mkdir ~/Documents/SU_Learning/131_INTRODUCTION_TO_COMPUTER_PROGRAMMING/Week-6")
    os.system("mkdir ~/Documents/SU_Learning/132_OBJECT_ORIENTED_PROGRAMMING/")
    os.system("mkdir ~/Documents/SU_Learning/132_OBJECT_ORIENTED_PROGRAMMING/Week-1")
    os.system("mkdir ~/Documents/SU_Learning/132_OBJECT_ORIENTED_PROGRAMMING/Week-2")
    os.system("mkdir ~/Documents/SU_Learning/132_OBJECT_ORIENTED_PROGRAMMING/Week-3")
    os.system("mkdir ~/Documents/SU_Learning/132_OBJECT_ORIENTED_PROGRAMMING/Week-4")
    os.system("mkdir ~/Documents/SU_Learning/132_OBJECT_ORIENTED_PROGRAMMING/Week-5")
    os.system("mkdir ~/Documents/SU_Learning/132_OBJECT_ORIENTED_PROGRAMMING/Week-6")
    os.system("mkdir ~/Documents/SU_Learning/133_ALGORITHMS_AND_DATA_STRUCTURES/")
    os.system("mkdir ~/Documents/SU_Learning/133_ALGORITHMS_AND_DATA_STRUCTURES/Week-1")
    os.system("mkdir ~/Documents/SU_Learning/133_ALGORITHMS_AND_DATA_STRUCTURES/Week-2")
    os.system("mkdir ~/Documents/SU_Learning/133_ALGORITHMS_AND_DATA_STRUCTURES/Week-3")
    os.system("mkdir ~/Documents/SU_Learning/133_ALGORITHMS_AND_DATA_STRUCTURES/Week-4")
    os.system("mkdir ~/Documents/SU_Learning/133_ALGORITHMS_AND_DATA_STRUCTURES/Week-5")
    os.system("mkdir ~/Documents/SU_Learning/133_ALGORITHMS_AND_DATA_STRUCTURES/Week-6")
    os.system("mkdir ~/Documents/SU_Learning/121_EDUC_COLLEGE_STUDIES/")
    os.system("mkdir ~/Documents/SU_Learning/121_EDUC_COLLEGE_STUDIES/Week-1")
    os.system("mkdir ~/Documents/SU_Learning/121_EDUC_COLLEGE_STUDIES/Week-2")
    os.system("mkdir ~/Documents/SU_Learning/121_EDUC_COLLEGE_STUDIES/Week-3")
    os.system("mkdir ~/Documents/SU_Learning/121_EDUC_COLLEGE_STUDIES/Week-4")
    os.system("mkdir ~/Documents/SU_Learning/121_EDUC_COLLEGE_STUDIES/Week-5")
    os.system("mkdir ~/Documents/SU_Learning/121_EDUC_COLLEGE_STUDIES/Week-6")
    os.system("mkdir ~/Documents/SU_Learning/133_ENGL_READING_COMPREHENSION/")
    os.system("mkdir ~/Documents/SU_Learning/133_ENGL_READING_COMPREHENSION/Week-1")
    os.system("mkdir ~/Documents/SU_Learning/133_ENGL_READING_COMPREHENSION/Week-2")
    os.system("mkdir ~/Documents/SU_Learning/133_ENGL_READING_COMPREHENSION/Week-3")
    os.system("mkdir ~/Documents/SU_Learning/133_ENGL_READING_COMPREHENSION/Week-4")
    os.system("mkdir ~/Documents/SU_Learning/133_ENGL_READING_COMPREHENSION/Week-5")
    os.system("mkdir ~/Documents/SU_Learning/133_ENGL_READING_COMPREHENSION/Week-6")
    os.system("mkdir ~/Documents/SU_Learning/145_ENGL__TECHNICAL_WRITING/")
    os.system("mkdir ~/Documents/SU_Learning/145_ENGL__TECHNICAL_WRITING/Week-1")
    os.system("mkdir ~/Documents/SU_Learning/145_ENGL__TECHNICAL_WRITING/Week-2")
    os.system("mkdir ~/Documents/SU_Learning/145_ENGL__TECHNICAL_WRITING/Week-3")
    os.system("mkdir ~/Documents/SU_Learning/145_ENGL__TECHNICAL_WRITING/Week-4")
    os.system("mkdir ~/Documents/SU_Learning/145_ENGL__TECHNICAL_WRITING/Week-5")
    os.system("mkdir ~/Documents/SU_Learning/145_ENGL__TECHNICAL_WRITING/Week-6")
    os.system("mkdir ~/Documents/SU_Learning/101_GEO_GEOLOGY_1/")
    os.system("mkdir ~/Documents/SU_Learning/101_GEO_GEOLOGY_1/Week-1")
    os.system("mkdir ~/Documents/SU_Learning/101_GEO_GEOLOGY_1/Week-2")
    os.system("mkdir ~/Documents/SU_Learning/101_GEO_GEOLOGY_1/Week-3")
    os.system("mkdir ~/Documents/SU_Learning/101_GEO_GEOLOGY_1/Week-4")
    os.system("mkdir ~/Documents/SU_Learning/101_GEO_GEOLOGY_1/Week-5")
    os.system("mkdir ~/Documents/SU_Learning/101_GEO_GEOLOGY_1/Week-6")
    os.system("mkdir ~/Documents/SU_Learning/110_MK_MARKETING_1/")
    os.system("mkdir ~/Documents/SU_Learning/110_MK_MARKETING_1/Week-1")
    os.system("mkdir ~/Documents/SU_Learning/110_MK_MARKETING_1/Week-2")
    os.system("mkdir ~/Documents/SU_Learning/110_MK_MARKETING_1/Week-3")
    os.system("mkdir ~/Documents/SU_Learning/110_MK_MARKETING_1/Week-4")
    os.system("mkdir ~/Documents/SU_Learning/110_MK_MARKETING_1/Week-5")
    os.system("mkdir ~/Documents/SU_Learning/110_MK_MARKETING_1/Week-6")
    os.system("mkdir ~/Documents/SU_Learning/121_MK__MARKETING_2/")
    os.system("mkdir ~/Documents/SU_Learning/121_MK__MARKETING_2/Week-1")
    os.system("mkdir ~/Documents/SU_Learning/121_MK__MARKETING_2/Week-2")
    os.system("mkdir ~/Documents/SU_Learning/121_MK__MARKETING_2/Week-3")
    os.system("mkdir ~/Documents/SU_Learning/121_MK__MARKETING_2/Week-4")
    os.system("mkdir ~/Documents/SU_Learning/121_MK__MARKETING_2/Week-5")
    os.system("mkdir ~/Documents/SU_Learning/121_MK__MARKETING_2/Week-6")
    os.system("mkdir ~/Documents/SU_Learning/2010_MK_SOCIAL_MEDIA_ADVERTISING/")
    os.system("mkdir ~/Documents/SU_Learning/2010_MK_SOCIAL_MEDIA_ADVERTISING/Week-1")
    os.system("mkdir ~/Documents/SU_Learning/2010_MK_SOCIAL_MEDIA_ADVERTISING/Week-2")
    os.system("mkdir ~/Documents/SU_Learning/2010_MK_SOCIAL_MEDIA_ADVERTISING/Week-3")
    os.system("mkdir ~/Documents/SU_Learning/2010_MK_SOCIAL_MEDIA_ADVERTISING/Week-4")
    os.system("mkdir ~/Documents/SU_Learning/2010_MK_SOCIAL_MEDIA_ADVERTISING/Week-5")
    os.system("mkdir ~/Documents/SU_Learning/2010_MK_SOCIAL_MEDIA_ADVERTISING/Week-6")
    os.system("mkdir ~/Documents/SU_Learning/110_INTRODUCTION_TO_PSYCHOLOGY/")
    os.system("mkdir ~/Documents/SU_Learning/110_INTRODUCTION_TO_PSYCHOLOGY/Week-1")
    os.system("mkdir ~/Documents/SU_Learning/110_INTRODUCTION_TO_PSYCHOLOGY/Week-2")
    os.system("mkdir ~/Documents/SU_Learning/110_INTRODUCTION_TO_PSYCHOLOGY/Week-3")
    os.system("mkdir ~/Documents/SU_Learning/110_INTRODUCTION_TO_PSYCHOLOGY/Week-4")
    os.system("mkdir ~/Documents/SU_Learning/110_INTRODUCTION_TO_PSYCHOLOGY/Week-5")
    os.system("mkdir ~/Documents/SU_Learning/110_INTRODUCTION_TO_PSYCHOLOGY/Week-6")
    os.system("mkdir ~/Documents/SU_Learning/191_INTRODUCTION_TO_JAVASCRIPT/")
    os.system("mkdir ~/Documents/SU_Learning/191_INTRODUCTION_TO_JAVASCRIPT/week-1")
    os.system("mkdir ~/Documents/SU_Learning/191_INTRODUCTION_TO_JAVASCRIPT/week-2")
    os.system("mkdir ~/Documents/SU_Learning/191_INTRODUCTION_TO_JAVASCRIPT/week-3")
    os.system("mkdir ~/Documents/SU_Learning/191_INTRODUCTION_TO_JAVASCRIPT/week-4")
    os.system("mkdir ~/Documents/SU_Learning/191_INTRODUCTION_TO_JAVASCRIPT/week-5")
    os.system("mkdir ~/Documents/SU_Learning/191_INTRODUCTION_TO_JAVASCRIPT/week-6")
    os.system("mkdir ~/Documents/SU_Learning/192_JAVASCRIPT_PROGRAMMING/")
    os.system("mkdir ~/Documents/SU_Learning/192_JAVASCRIPT_PROGRAMMING/Week-1")
    os.system("mkdir ~/Documents/SU_Learning/192_JAVASCRIPT_PROGRAMMING/Week-2")
    os.system("mkdir ~/Documents/SU_Learning/192_JAVASCRIPT_PROGRAMMING/Week-3")
    os.system("mkdir ~/Documents/SU_Learning/192_JAVASCRIPT_PROGRAMMING/Week-4")
    os.system("mkdir ~/Documents/SU_Learning/192_JAVASCRIPT_PROGRAMMING/Week-5")
    os.system("mkdir ~/Documents/SU_Learning/192_JAVASCRIPT_PROGRAMMING/Week-6")
    os.system("mkdir ~/Documents/SU_Learning/101_WORD_PROCESSING/")
    os.system("mkdir ~/Documents/SU_Learning/101_WORD_PROCESSING/Week-1")
    os.system("mkdir ~/Documents/SU_Learning/101_WORD_PROCESSING/Week-2")
    os.system("mkdir ~/Documents/SU_Learning/101_WORD_PROCESSING/Week-3")
    os.system("mkdir ~/Documents/SU_Learning/101_WORD_PROCESSING/Week-4")
    os.system("mkdir ~/Documents/SU_Learning/101_WORD_PROCESSING/Week-5")
    os.system("mkdir ~/Documents/SU_Learning/101_WORD_PROCESSING/Week-6")
    os.system("mkdir ~/Documents/SU_Learning/310_WEB__DIGITAL_MARKETING_FUNDAMENTALS/")
    os.system("mkdir ~/Documents/SU_Learning/310_WEB__DIGITAL_MARKETING_FUNDAMENTALS/Week-1")
    os.system("mkdir ~/Documents/SU_Learning/310_WEB__DIGITAL_MARKETING_FUNDAMENTALS/Week-2")
    os.system("mkdir ~/Documents/SU_Learning/310_WEB__DIGITAL_MARKETING_FUNDAMENTALS/Week-3")
    os.system("mkdir ~/Documents/SU_Learning/310_WEB__DIGITAL_MARKETING_FUNDAMENTALS/Week-4")
    os.system("mkdir ~/Documents/SU_Learning/310_WEB__DIGITAL_MARKETING_FUNDAMENTALS/Week-5")
    os.system("mkdir ~/Documents/SU_Learning/310_WEB__DIGITAL_MARKETING_FUNDAMENTALS/Week-6")
    os.system("mkdir ~/Documents/SU_Learning/320_WEB__DIGITAL_MARKETING/")
    os.system("mkdir ~/Documents/SU_Learning/320_WEB__DIGITAL_MARKETING/Week-1")
    os.system("mkdir ~/Documents/SU_Learning/320_WEB__DIGITAL_MARKETING/Week-2")
    os.system("mkdir ~/Documents/SU_Learning/320_WEB__DIGITAL_MARKETING/Week-3")
    os.system("mkdir ~/Documents/SU_Learning/320_WEB__DIGITAL_MARKETING/Week-4")
    os.system("mkdir ~/Documents/SU_Learning/320_WEB__DIGITAL_MARKETING/Week-5")
    os.system("mkdir ~/Documents/SU_Learning/320_WEB__DIGITAL_MARKETING/Week-6")

    time.sleep(2)
    print("[+] Folders Created, Happy Learning! :)")

if __name__ == '__main__':
    menu()